import type { GetStaticProps, GetStaticPaths, NextPage } from "next";
import type { PTProgram, FTProgram } from "@prisma/client";
import Menu from "@component/components/Menu/Menu";
import Head from "next/head";
import { useRouter } from "next/router";
import { backChevron } from "@component/data/svgs";

export interface SingleProgramPageProps {
  programid: string;
}

export type SingleProgramPaths = {
  params: {
    programid: string;
  };
};

import { PrismaClient } from "@prisma/client";
import FeaturedProgramComponent from "@component/components/FeaturedProgram/FeaturedProgramComponent";
import { useSession } from "next-auth/react";

const prisma = new PrismaClient();

const SingleProgramPage: NextPage<SingleProgramPageProps> = ({ programid }) => {
  const pageTitle = `Featured Program - Act. Sing. Dance. Repeat. ~ ${programid}`;
  const router = useRouter();
  const { data: sessionData } = useSession();

  const handleGoBack = () => {
    router.back();
  };

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="min-h-screen bg-cyan-50 bg-opacity-80">
          <Menu />
          <div
            className="absolute left-0 right-0 hidden h-10 bg-cyan-950 mobileMenu:block"
            style={{
              boxShadow:
                "inset 0px -1px 2px rgba(0,255,255,0.5), inset 0px -2px 4px rgba(0,255,255,0.5), inset 0px -4px 8px rgba(0,255,255,0.5)",
            }}
          ></div>
          <div className="h-10"></div>
          {sessionData?.user && (
            <div className="mt-2 hidden w-screen justify-end pr-2 text-sm italic mobileMenu:flex mobileMenu:pr-4">
              <span>Logged in as: {sessionData.user.name}</span>
            </div>
          )}

          <button
            onClick={handleGoBack}
            className="m-2 flex rounded border-2 border-cyan-800 p-3 hover:scale-105 hover:shadow-md hover:shadow-cyan-600 mobileMenu:ml-10"
          >
            {backChevron} Go Back
          </button>
          <FeaturedProgramComponent programId={programid} />
        </div>
      </main>
    </>
  );
};

const createPaths = async (): Promise<SingleProgramPaths[]> => {
  const allPTPrograms = await prisma.pTProgram.findMany({
    where: {
      articlePitch: {
        not: {
          equals: null,
        },
      },
    },
  });
  const allFTPrograms = await prisma.fTProgram.findMany({
    where: {
      articlePitch: {
        not: {
          equals: null,
        },
      },
    },
  });

  const allPrograms: (FTProgram | PTProgram)[] = [
    ...allPTPrograms,
    ...allFTPrograms,
  ];

  const allProgramPaths: SingleProgramPaths[] = allPrograms.map((program) => {
    return { params: { programid: program.id.toString() } };
  });

  return allProgramPaths;
};

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = await createPaths();
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = (context) => {
  const { params } = context;

  const programid = params?.programid;

  return {
    props: {
      programid,
    },
  };
};

export default SingleProgramPage;
