import { type NextPage } from "next";
import Head from "next/head";
import Menu from "@component/components/Menu/Menu";
import AboutComponent from "@component/components/About/AboutComponent";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>Performer 1</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-cyan-50 text-cyan-950">
        <Menu />
        <AboutComponent />
      </main>
    </>
  );
};

export default About;
