import { type NextPage } from "next";
import Head from "next/head";
import Menu from "@component/components/Menu/Menu";
import AboutComponent from "@component/components/About/AboutComponent";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About ~ Act. Sing. Dance. Repeat.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Comme:wght@200;400;500;600;700;800&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-cyan-50 text-cyan-950">
        <Menu />
        <AboutComponent />
      </main>
    </>
  );
};

export default About;
