import { type NextPage } from "next";
import Head from "next/head";
import Menu from "@component/components/Menu/Menu";
import BlogComponent from "@component/components/Blog/BlogComponent";
import { api } from "@component/utils/api";
import { useState } from "react";
import type { Post } from "@prisma/client";
import { useEffectOnce } from "@component/components/AddProgramResult/helpers";
import LoadingLines from "@component/components/Loading/LoadingLines";
import { doubleChevronDown } from "@component/data/svgs";

const Blog: NextPage = () => {
  const [postsToDisplay, setPostsToDisplay] = useState<Post[]>([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [loading, setLoading] = useState<boolean>(true);
  const utils = api.useContext();

  const lastId = "clm9b3wz10007ulit9dn7u8mv";
  const pageSize = 6;
  const isLastExpansion =
    postsToDisplay && postsToDisplay[postsToDisplay.length - 1]?.id === lastId;

  const fetchPosts = async (page: number, pageSize: number) => {
    const response = await utils.post.getPaginatedPosts.fetch({
      page,
      pageSize,
    });

    return response;
  };

  useEffectOnce(() => {
    fetchPosts(currentPage, pageSize)
      .then((newPosts) => {
        setPostsToDisplay(newPosts);
      })
      .then(() => setLoading(false))
      .catch((error) => console.error("Error fetching posts: ", error));
  });

  const showNext = () => {
    if (!isLastExpansion) {
      const newCurrentPage = currentPage + 1;
      setCurrentPage(newCurrentPage);
      fetchPosts(newCurrentPage, pageSize)
        .then((newPosts) => {
          setPostsToDisplay((prev) => [...prev, ...newPosts]);
        })
        .catch((error) => console.error("Error fetching posts: ", error));
    }
  };

  return (
    <>
      <Head>
        <title>About ~ Act. Sing. Dance. Repeat.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-cyan-50 pb-10 text-cyan-950">
        <Menu />
        <BlogComponent postArray={postsToDisplay} />
        {loading && <LoadingLines />}
        {!isLastExpansion && !loading && (
          <button
            onClick={() => showNext()}
            className="m-5 flex w-52 justify-around rounded-md border-2 border-cyan-700 p-3 text-cyan-800 transition-all hover:scale-105 hover:shadow-md hover:shadow-cyan-800"
          >
            <span>{doubleChevronDown}</span>
            <span>More</span>
            <span>{doubleChevronDown}</span>
          </button>
        )}
      </main>
    </>
  );
};

export default Blog;
