import { type NextPage } from "next";
import Head from "next/head";
import Menu from "@component/components/Menu/Menu";
import BlogComponent from "@component/components/Blog/BlogComponent";
import { api } from "@component/utils/api";
import LoadingLines from "@component/components/Loading/LoadingLines";

const Blog: NextPage = () => {
  const { data: posts } = api.post.getAll.useQuery();

  if (!posts) {
    return (
      <div className=" h-screen w-screen bg-cyan-50">
        <LoadingLines />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>About ~ Act. Sing. Dance. Repeat.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-cyan-50 text-cyan-950">
        <Menu />
        <BlogComponent initialPostArray={posts} />
      </main>
    </>
  );
};

export default Blog;
