import ContactComponent from "@component/components/Contact/ContactComponent";
import Menu from "@component/components/Menu/Menu";
import React from "react";
import Head from "next/head";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact ~ Act. Sing. Dance. Repeat.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="min-h-screen bg-slate-900">
          <Menu />
          <ContactComponent />
        </div>
      </main>
    </>
  );
}
