import ContactComponent from "@component/components/Contact/ContactComponent";
import Menu from "@component/components/Menu/Menu";
import React from "react";
import SenderScript from "@component/components/Contact/SenderScript";
import Head from "next/head";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact ~ Act. Sing. Dance. Repeat.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Comme:wght@200;400;500;600;700;800&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <div className="min-h-screen bg-slate-900">
          <Menu />
          <SenderScript />
          <ContactComponent />
        </div>
      </main>
    </>
  );
}
