import CourseFinderComponent from "@component/components/ProgramFinder/CourseFinderComponent";
import { NextPage } from "next";
import Menu from "@component/components/Menu/Menu";
import Head from "next/head";

const ProgramSearch: NextPage = () => {
  return (
    <>
      <Head>
        <title>Course Finder ~ Act. Sing. Dance. Repeat.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Comme:wght@200;400;500;600;700;800&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <div className="bg-cyan-50 bg-opacity-80">
          <Menu />
          <CourseFinderComponent />
        </div>
      </main>
    </>
  );
};

export default ProgramSearch;
