import React from "react";
import Picker from "@component/components/ProgramSelector/Picker";
import { styles } from "@component/data/constants";
import Menu from "@component/components/Menu/Menu";
import Face from "@component/components/ProgramSelector/Face";
import Head from "next/head";

export default function CourseSelector() {
  return (
    <>
      <Head>
        <title>Course Selector ~ Act. Sing. Dance. Repeat.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Comme:wght@200;400;500;600;700;800&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <div className="min-h-screen bg-cyan-50 bg-opacity-80 text-cyan-900">
          <Menu />
          <div
            className="absolute left-0 right-0 hidden h-10 mobileMenu:block"
            style={{
              boxShadow:
                "inset 0px -1px 2px rgba(0,255,255,0.5), inset 0px -2px 4px rgba(0,255,255,0.5), inset 0px -4px 8px rgba(0,255,255,0.5)",
            }}
          ></div>
          <div className="mb-10 hidden h-10 bg-cyan-950 mobileMenu:block"></div>
          <div className="flex w-full flex-col items-center overflow-x-hidden">
            <h1
              className="mx-10 mt-3 w-9/12 text-center text-5xl font-extrabold tracking-tight md:mt-10 md:text-6xl"
              style={{ animation: "pullDownTop 1s ease-in-out" }}
            >
              What Kind of Program are you Looking For?
            </h1>
            <div
              className="m-8 h-2 w-10/12 rounded bg-indigo-900 bg-opacity-90 opacity-0"
              style={{ animation: "flyInFadeIn .3s ease-in-out 1s forwards" }}
            ></div>
            <div
              className="m-10 w-11/12 max-w-3xl place-self-center rounded-lg bg-gradient-to-b from-cyan-600 to-cyan-900 p-5 text-cyan-50 opacity-0 shadow-xl shadow-cyan-700 md:mb-16"
              style={{
                animation: "fadeInGrow .8s ease-in-out 1.3s forwards",
              }}
            >
              <Picker buttonOptions={styles} currentLink="" last={false} />
            </div>
            <div className="-mt-16 hidden md:block">
              <Face />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
