import CourseFinderComponent from "@component/components/ProgramFinder/CourseFinderComponent";
import type { NextPage } from "next";
import Menu from "@component/components/Menu/Menu";
import Head from "next/head";

const ProgramSearch: NextPage = () => {
  return (
    <>
      <Head>
        <title>Course Finder ~ Act. Sing. Dance. Repeat.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-cyan-50 bg-opacity-80">
          <Menu />
          <CourseFinderComponent />
        </div>
      </main>
    </>
  );
};

export default ProgramSearch;
