import { type NextPage } from "next";
import Head from "next/head";
import Menu from "@component/components/Menu/Menu";
import HomeComponent from "@component/components/Homepage/HomeComponent";
import Spotlights from "@component/components/Homepage/Spotlights";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Performer 1</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center overflow-x-hidden bg-slate-900 text-cyan-50">
        <Menu />
        <div className="flex max-h-screen flex-col content-center overflow-x-hidden overflow-y-hidden bg-slate-900">
          <div className="spotlights-container relative">
            <Spotlights />
          </div>
          <div className="mt-7 w-2/3 place-self-center  2xl:mt-20">
            <h1
              className="mb-8 mt-10 text-center text-4xl font-extrabold md:text-5xl xl:text-6xl"
              style={{ animation: "pullDownTop 1s forwards 1s", opacity: 0 }}
            >
              Resources for Canadian Performers
            </h1>
            <h2
              className="flex items-center justify-center"
              style={{ animation: "fadeIn 1s forwards 2s", opacity: 0 }}
            >
              <Link href={"/about"}>
                <button className="m-3 rounded p-3 outline hover:scale-110">
                  Get Started Here
                </button>
              </Link>
            </h2>
          </div>
          <HomeComponent />
        </div>
      </main>
    </>
  );
};

export default Home;
