import { type NextPage } from "next";
import Head from "next/head";
import Menu from "@component/components/Menu/Menu";
import HomeComponent from "@component/components/Homepage/HomeComponent";
import Spotlights from "@component/components/Homepage/Spotlights";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Performer 1</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-slate-900 text-cyan-50">
        <Menu />
        <Spotlights />
        <div style={{ animation: "pullDownTop 2.5s forwards" }}>
          <h1 className="m-7 text-5xl font-extrabold sm:text-[3rem]">
            Resources for Canadian Performers
          </h1>
          <h2 className="flex items-center justify-center">
            <div className="m-3 text-5xl font-extrabold sm:text-[2rem]">
              New?
            </div>
            <button className="m-3 rounded p-3 outline">
              Get Started Here
            </button>
          </h2>
        </div>
        <HomeComponent />
      </main>
    </>
  );
};

export default Home;
