import { type NextPage } from "next";
import Head from "next/head";
import Menu from "@component/components/Menu/Menu";
import HomeComponent from "@component/components/Homepage/HomeComponent";
import Spotlights from "@component/components/Homepage/Spotlights";
import Link from "next/link";
import FooterComponent from "@component/components/Footer/FooterComponent";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Act. Sing. Dance. Repeat.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between overflow-hidden bg-slate-900 text-cyan-50">
        <div className="flex flex-grow flex-col">
          <Menu />
          <Spotlights />
          <div className="flex flex-grow flex-col justify-center">
            <div className="mt-7 w-2/3 place-self-center">
              <h1
                className="mb-8 mt-5 text-center text-4xl font-extrabold md:max-mobileMenu:mt-0  mobileMenu:text-5xl mobileMenu:text-6xl"
                style={{ animation: "pullDownTop 1s forwards 1s", opacity: 0 }}
              >
                Resources for Canadian Performers
              </h1>
              <h2
                className="flex items-center justify-center"
                style={{ animation: "fadeIn 1s forwards 2s", opacity: 0 }}
              >
                <Link href={"/about"}>
                  <button className="m-3 rounded p-3 text-lg outline hover:scale-110 md:m-0">
                    Get Started Here
                  </button>
                </Link>
              </h2>
            </div>
            <HomeComponent />
          </div>
        </div>
        <div className="z-20">
          <FooterComponent />
        </div>
      </main>
    </>
  );
};

export default Home;
